### ISSUE TITLE
2D renderer -> _CameraSortingLayerTexture 

### ISSUE THREAD

**Issue by GieziJo** [gamedevserj/Shader-Graph-Experiments#1]
Since unity introduced the 2D renderer pipeline, capturing the screen with `_CameraOpaqueTexture` does not work anymore in 2D.
Instead, you need to use the `_CameraSortingLayerTexture` tag.

The shaders can then be made to work as follow:

- use _CameraSortingLayerTexture tag, remove the "Exposed" checkmark.
- In the 2D renderer data, set the "Foremost Sorting Layer" to the last layer you want to be renderer with distortion.
- Set the "Sorting Layer" of the sprite renderer which contains your distortion material to be above the last layer of the "foremost sorting layer".

Hope this is useful to somebody.

**Comment by gamedevserj** [comment]
Thanks! I updated the readme with your info.

**Comment by Alexio-Gomez** [comment]
I don't see the CameraSortinglayerTexture option in my 2D render data. I'm using unity 2020 so was it only added in the 2021 version?

**Comment by gamedevserj** [comment]
> I don't see the CameraSortinglayerTexture option in my 2D render data. I'm using unity 2020 so was it only added in the 2021 version?

It's been a while since I used URP and I don't have 2020 installed, but as far as I can remember _CameraSortinglayerTexture is not an option, it is a name you give to the node in the your graph which was previously named _CameraOpaqueTexture.
